name: Converting To PDF

on:
  push:
    branches: 
      - generate-pdf

jobs:
  convert:
    name: Convert portfolio to pdf
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Update
      run: sudo apt-get update
    - name: Install
      run: sudo apt-get install xvfb wkhtmltopdf
    - name: Convert
      run: |
        mkdir cv
        portfolioURL=$(grep 'url:' _config.yml | tail -n1 | awk '{ print s $2}' | tr -d \")
        xvfb-run wkhtmltopdf ${portfolioURL} cv/resume.pdf
    - name: Archive convert results
      uses: actions/upload-artifact@v2
      with:
        name: resume
        path: ${{ github.workspace }}/cv
  
  # job_2:
  #   name: download and write to repo
  #   needs: convert
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download result for job 1
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: resume
  #     - shell: bash
  #       run: |
  #           mv resume.pdf

  # job_3:
  #   name: push changes
  #   needs: job_2
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@master
  #       with:
  #         fetch-depth: 1
  #     - name: Push changes to repo
  #       run: |
  #         REMOTE=https://${{ secrets.EXAMPLE_SECRET }}@github.com/${{ github.repository }}
  #         git config user.email "${{ github.actor }}@users.noreply.github.com"
  #         git config user.name "${{ github.actor }}"

  #         git pull ${REMOTE}
  #         git checkout master
  #         git add .
  #         git status
  #         git commit -am "Add new comment"
  #         git push ${REMOTE} master